"""add task.jira_id

Revision ID: 1d3715f85055
Revises: 308b8c251c7b
Create Date: 2022-10-16 16:49:48.434118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1d3715f85055"
down_revision = "308b8c251c7b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("jira_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "jira_id")
    # ### end Alembic commands ###
