version: '3'

services:
  db:
    image: postgres:14.1-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./temp-data/postgresql:/var/lib/postgresql/data

  zookeeper:
    platform: linux/x86_64
    image: zookeeper:3.6.2
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOO_ADMINSERVER_ENABLED: "false"
      ALLOW_ANONYMOUS_LOGIN: "yes"
    volumes:
      - ./temp-data/zookeeper/data:/data
      - ./temp-data/zookeeper/datalog:/datalog

  kafka:
    platform: linux/x86_64
    image: bitnami/kafka:3.0.2
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    volumes:
      - ./temp-data/kafka:/var/lib/kafka/data
    depends_on:
      - zookeeper
    restart: always

  akhq:
    platform: linux/x86_64
    image: tchiotludo/akhq:0.17.0
    container_name: kafka-akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            local-kafka:
              properties:
                bootstrap.servers: "kafka:9092"
    ports:
      - "8092:8080"
