"""add task.jira_id

Revision ID: a097ce6b994b
Revises: 146c888bfdc1
Create Date: 2022-10-16 16:39:17.553430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a097ce6b994b"
down_revision = "146c888bfdc1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("jira_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "jira_id")
    # ### end Alembic commands ###
